Student_name = input("Enter your name: ")
rollno = input("Enter your roll no: ")
math = input("Enter your maths marks: ")
english = input("Enter your english marks: ")
print("------ Student Report ------")
print("Name:", Student_name)
print("Rollno:", rollno)
print("Maths:", math)
print("English:", english)